description: >
  Build public site using zola.

executor:
  name: zola
  zola_version: <<parameters.zola_version>>
parameters:
  zola_version:
    type: string
    description: "The of zola to use"
  update_submodules:
    type: boolean
    default: true
    description: "If true, the git submodules will be updated."
steps:
  - checkout
  - when: << parameters.update_submodules >>
    steps:
      - run: git submodule sync
      - run: git submodule update --init
  - run: zola --version
  - run: zola build
