description: >
  Build public site using zola.

executor:
  name: zola
  zola_version: <<parameters.zola_version>>

parameters:
  zola_version:
    type: string
    description: "The of zola to use"
  update_submodules:
    type: boolean
    default: true
    description: "If true, the git submodules will be updated."
  list_directory:
    type: boolean
    default: false
    description: "If true, list the directory after the update."
  output_dir:
    type: string
    default: ""
    description: "If true, list the directory after the update."

steps:
  - checkout

  - when:
      condition: << parameters.update_submodules >>
      steps:
        - run:
            name: Sync git submodules
            command: |
              git submodule sync

        - run:
            name: Update git submodules
            command: |
              git submodule update --init

  - run:
      name: Confirm zola version
      command: |
        zola --version

  - run:
      name: Export OUTPUT_DIRECTORY
      command: |
        echo "export OD=<< parameters.output_dir >>" >> "$BASH_ENV"

  - run:
      name: Build site
      command: <<include(scripts/build.sh)>>

  - when:
      condition: << parameters.list_directory >>
      steps:
        - run:
            name: List directory contents
            command: |
              pwd
              ls -la
