description: >
  Build public site using zola.

executor:
  name: zola
  zola_version: <<parameters.zola_version>>

parameters:
  zola_version:
    type: string
    description: "The of zola to use"
  update_submodules:
    type: boolean
    default: true
    description: "If true, the git submodules will be updated."
  list_directory:
    type: boolean
    default: false
    description: "If true, list the directory after the update."
  output_dir:
    type: string
    default: ""
    description: "If true, list the directory after the update."
  add_submodules:
    type: boolean
    default: false
    description: "If true, add a submodule to the git repository."
  submodule_name:
    type: string
    default: ""
    description: "The name of the submodule to add."
  submodule_source:
    type: string
    default: ""
    description: "The source of the submodule to add."
  submodule_destination:
    type: string
    default: ""
    description: "The destination of the submodule to add."

steps:
  - checkout

  - when:
      condition: << parameters.update_submodules >>
      steps:
        - run:
            name: Sync git submodules
            command: |
              git submodule sync

        - run:
            name: Update git submodules
            command: |
              git submodule update --init

  - when:
      condition: << parameters.add_submodules >>
      steps:
        - run:
            name: Add git submodule << parameters.submodule_name >>
            command: git submodule add << parameters.submodule_source >> << parameters.submodule_destination >>

  - run:
      name: Confirm zola version
      command: |
        zola --version

  - run:
      name: Export output directory environment variable
      command: |
        echo "export OD=<< parameters.output_dir >>" >> "$BASH_ENV"

  - run:
      name: Build site
      command: <<include(scripts/build.sh)>>

  - run:
      name: Check internal and external links
      command: |
        zola check

  - when:
      condition: << parameters.list_directory >>
      steps:
        - run:
            name: List directory contents
            command: |
              pwd
              ls -la
